apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oaf-tls
  namespace: platform
  labels:
    app.kubernetes.io/name: oaf-tls
    app.kubernetes.io/version: "2025.10"
    app.kubernetes.io/component: certificate
    app.kubernetes.io/part-of: supabase-stack
    app.kubernetes.io/managed-by: cert-manager
  annotations:
    cert-manager.io/revision-history-limit: "3"
spec:
  secretName: oaf-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - pyro1121.com
    - "*.pyro1121.com"  # Wildcard for subdomains
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  duration: 2160h  # 90 days
  renewBefore: 360h  # 15 days before expiry
  subject:
    organizations:
      - "Supabase Platform"
  usages:
    - digital signature
    - key encipherment
    - server auth
  secretTemplate:
    labels:
      app.kubernetes.io/name: oaf-tls
      app.kubernetes.io/component: certificate
    annotations:
      cert-manager.io/certificate-name: oaf-tls
      cert-manager.io/issuer-name: letsencrypt
      cert-manager.io/issuer-kind: ClusterIssuer